# Generated by Django 6.0.3 on 2026-03-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.CharField(
                default="Автор не указан", max_length=100, verbose_name="Автор"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="summary",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Краткое описание"
            ),
        ),
    ]
