# Generated by Django 6.0.3 on 2026-04-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_post_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.CharField(
                default="Автор не указан", max_length=100, verbose_name="Автор"
            ),
        ),
    ]
